### ISSUE TITLE
Open VSX Support

### ISSUE THREAD

**Issue by chaosharmonic** [shubham-saudolla/Lilac-Theme#3]
Hey there - any way you'd be willing to publish this to the Open VSX Registry? It would make this accessible to downstream projects like Theia and VSCodium, which can't access the VS Code Marketplace for licensing reasons. (In particular, various Arch Linux distros ship with Code-OSS builds by default.)

Here's a link to [some relevant documentation from the OVSX wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by shubham-saudolla** [comment]
Sure, I'll do that!

**Comment by shubham-saudolla** [comment]
I have published the them to OVSX, [here](https://open-vsx.org/extension/shubham-saudolla/lilac) and will update the readme in the next version.

Cheers!
